### PR TITLE
Add Support for Injecting Buffers

### PR DESCRIPTION
**Pull request by bashbaug**
## Description of Changes

Adds the ability to inject modified buffers before a kernel is executed.  To inject a modified buffer, set the control `InjectBuffers`, and copy the buffer to inject to an `Inject` directory, just like injecting modified program source.  Currently, the file name should be the same as the file name for dumped buffers - something like `Enqueue_XXXX_Kernel_MyKernelName_Arg_N_Buffer_YYYY.bin`.

The size of the file needs to be equal to or smaller than the buffer size.  If the size of the file is greater than the buffer size then the buffer is not modified.  If the size of the file is smaller than the buffer size then only the first part of the buffer is modified.

## Testing Done

Tested with a simple application.  Verified that the buffer contents were modified with the contents of the file.

### CODE REVIEW

**Comment by bashbaug** [comment]
@karolherbst can you give this a try and see if it does what you want it to do?

I am going to keep this a draft while I run a few more tests and make a few more improvements:

* [ ] Need to test SVM and USM injection.
* [ ] Need to write better documentation, perhaps something similar to the page about injecting modified program source.
* [ ] Need to figure out any other file names should be searched, particularly for programs that execute non-deterministically.
* [ ] Should we also support injecting modified images, or just modified buffers?

**Comment by karolherbst** [comment]
>     * [ ]  Should we also support injecting modified images, or just modified buffers?

I think images is even more important here. Buffers are way more likely to contain the same content across drivers/platforms and my main motivation was here to figure out if device specific differences in results (float operation, image filtering, etc...) are responsible for a bug or not.

So from a workflow perspective I'd like to be able to do something like this:

tracing an application on two different drivers, `A` being correct and `B` having a visually significant difference.

1. dump the checksum + content of buffers/images
2. find the first different output
3. run the application with the first different buffer/image from `A` on `B`
4. repeat 1. to 3. until I find the actually significant difference as checksums might be different due to image filtering, variance in floating point operations, etc... without actually causing any issues.
5. debug the driver

And the bug I was debugging was actually image related, I was just lucky enough that the first difference was already the bug. But the same output was also differing on two drivers not showing any issues due to linear filtering being used.

**Comment by bashbaug** [comment]
> I think images is even more important here.

Cool, I think images should be fairly easy to add using the same methodology.  It'll actually be easier in some ways, since there aren't three different ways of representing images like there are for buffers (cl_mems, SVM, USM).

I'll probably require that the file size matches the image size, since a mismatch almost certainly means that the wrong file is being used.  Does that make sense?  Should I require that the file size matches for buffers, also?

**Comment by bashbaug** [comment]
I think this is ready to go.  I've tested buffer, USM, SVM, and image injection and everything seems to be working.  I've written up initial documentation.  I haven't added any new filenames to search just yet, but that should be easy to add if needed.

**Comment by karolherbst** [comment]
Mhh, I read through the readme and what I had in mind was to actually replace the output of a command, so it propagates through the entire application, which means you wouldn't have to figure out where the output you are interested in is all used, because the application also map it and fetch the content.

But I think what you added here is also useful.

Luckily in my test it was just used once and I don't think the application reads its content directly. But when trying it out, it doesn't seem to work correctly at least the final output is all black and I simply injected the same image as captured.

**Comment by bashbaug** [comment]
> what I had in mind was to actually replace the output of a command, so it propagates through the entire application

Interesting.  I figured the primary goal would be to identify the "problematic" kernel and hence modifying the input to the kernel would be the most useful, but I can certainly see how modifying an output from a kernel could be useful too, especially if it gets used in multiple places.

Of course, if we did this, we'd probably also want to support modifying outputs for other commands also, such as memory copies, or perhaps even operations like unmapping buffers or images.  That could get complicated, fast.

At the very least I think I should update the README to add an explicit note that injecting a buffer (or image) will modify the buffer for the requested kernel enqueue, but also for all subsequent uses of the buffer, since this isn't immediately obvious.

> But when trying it out, it doesn't seem to work correctly at least the final output is all black and I simply injected the same image as captured.

Can you say a little more what your test is doing?  I did test all types of injection, including images, but only in pretty simple cases, nothing complicated, so it's possible there are bugs.

**Comment by karolherbst** [comment]
> > what I had in mind was to actually replace the output of a command, so it propagates through the entire application
> 
> Interesting. I figured the primary goal would be to identify the "problematic" kernel and hence modifying the input to the kernel would be the most useful, but I can certainly see how modifying an output from a kernel could be useful too, especially if it gets used in multiple places.
> 

my line of thinking was, that applications might do something with the output of commands, so modifying the output should reduce the risk of inconsistency between later invocations and whatever the application thinks is happening.

> Of course, if we did this, we'd probably also want to support modifying outputs for other commands also, such as memory copies, or perhaps even operations like unmapping buffers or images. That could get complicated, fast.
> 
> At the very least I think I should update the README to add an explicit note that injecting a buffer (or image) will modify the buffer for the requested kernel enqueue, but also for all subsequent uses of the buffer, since this isn't immediately obvious.
> 
> > But when trying it out, it doesn't seem to work correctly at least the final output is all black and I simply injected the same image as captured.
> 
> Can you say a little more what your test is doing? I did test all types of injection, including images, but only in pretty simple cases, nothing complicated, so it's possible there are bugs.

I've was looking into this darktable bug: https://github.com/darktable-org/darktable/issues/16717#event-12837434616

I've been working with a small wrapper script (attached in the end) and the argument I've tried to Inject was `Enqueue_0006_Kernel_whitebalance_1f_Arg_0_Image_0001_4064x3056x1_32bpp.raw` (unmodified from the dump).

To get the `PXL_20240421_095931520.RAW-02.ORIGINAL.dng.xmp` file you will have to open the dng file with darktable once first.

You might also have to enable OpenCL support in darktable as well, which can be found inside the processing options in the settings.

script:
```sh
#!/bin/sh
rm out.png

#export CLI_CallLogging=1

export CLI_DumpBufferHashes=0
export CLI_DumpBuffersBeforeEnqueue=0
export CLI_DumpBuffersAfterEnqueue=0

export CLI_DumpImageHashes=0
export CLI_DumpImagesBeforeEnqueue=1
export CLI_DumpImagesAfterEnqueue=0
export CLI_InjectImages=1

export CLI_DumpImagesForKernel="whitebalance_1f"

mkdir ${name}_dump >/dev/null 2>&1
/data/git/opencl-intercept-layer/build/cliloader/cliloader \
	--dump-dir dump \
	darktable-cli \
		PXL_20240421_095931520.RAW-02.ORIGINAL.dng \
		PXL_20240421_095931520.RAW-02.ORIGINAL.dng.xmp \
		out.png \
		--core \
			-d pipe \
			-d opencl \
			-d tiling
```

**Comment by bashbaug** [comment]
Thanks, I've reproduced the empty output on my system.  I'm looking at this now.

**Comment by bashbaug** [comment]
That's embarassing - I must have removed the file read when injecting images in the last bit of cleanup and refactoring.  This is fixed now, and the test case above is generating the proper output image.

**Comment by karolherbst** [comment]
yeah it works now, thanks!

And I was also able to use the buffer from a correct run, which then made the output be correct on a broken driver, so this seems to work as well.

I'm sure there are some applications which might show other sorts of breakage when replacing inputs instead of outputs, but at least this isn't happening in this example.

**Comment by bashbaug** [comment]
Cool, I'm going to go ahead and merge this then, and we can always make additional refinements later.  Thanks!

**Pull request merged**
