### PR TITLE
add more capture replay controls

### PR DESCRIPTION
**Pull request by bashbaug**
## Description of Changes

This is a fairly large refactor of the "kernel capture and replay" to add more controls, fix a few bugs, improve efficiency, and generally fit more closely with other similar functionality in the OpenCL Intercept Layer.

In no particular order:
- Added far more controls to control kernel capture and replay, similar to aubcapture and dumping memory objects.
- ~~Reused memory object dumps for captured buffer and image data vs. having dumps specific for capture and replay.~~
    - This change was reverted, and the captured buffer and image data for replay and validation is again dumped into the replay directory so it remains a self-contained reproducer - see discussion below.
- Fixed a few bugs when replaying kernels using images.
- Added a few checks for missing replay data and other issues to the replay script.
- Tidied up documentation and terminology in the scripts.

I've done my best to retain compatibility with previous controls but they may not work reliably, and it would be better to switch to the new controls.

## Testing Done

Tested capture, replay, and validation on an application with buffers and another application with images.
Tested capture, replay, and validation based on a kernel name and based on an enqueue number.
Tested various error cases, such as an enqueue number that is never reached and a kernel name that is never enqueued.
Tested on Linux edit: and Windows.

### CODE REVIEW

**Comment by Novermars** [comment]
Hi Ben, I haven't been able to run these changes, but I think not having the binary objects specifically for replaying a kernel (in the same folder as the rest of the replay files) is a mistake.

One of the strengths of my approach is that you can simply zip the replay folder for an enqueue and immediately share it or replay it on another computer/device/vendor/... This makes it a lot easier to share reproducers with e.g. a driver team.

If I have to look for these buffers/images somewhere else, it just adds another point of failure, especially when there are 100'000 buffers in those files. In my opinion, it's very much worth it for the tiny overhead you incur!

Otherwise the changes look great! One thing that I always wanted to do myself is use a single json file for all the metadata, instead of this mess of random files right now. But is of course low priority!

**Comment by bashbaug** [comment]
Thanks for the feedback - I was hoping you would see this and respond!

> One of the strengths of my approach is that you can simply zip the replay folder for an enqueue and immediately share it or replay it on another computer/device/vendor/... This makes it a lot easier to share reproducers with e.g. a driver team.

This is a good point and I wasn't considering this use-case.  I suppose, though, it is possible to zip up the entire "dump" folder and use this to generate a reproducer, so maybe not _that_ bad?  If I updated the documentation to say this explicitly would that be acceptable?

**Comment by Novermars** [comment]
Sure, no worries :) 

By dump folder you mean the pre/post enqueue buffer folders? Since you hardcoded those locations in the run.py script? If for some reason you need to dump all the binary buffers beforehand, you know have a 100GB reproducer, not ideal I would say.

If I may ask, what's the problem you're trying to solve by not dumping into the replay folder? All the ugly code duplication to figure out the right folder to dump them into?

**Comment by bashbaug** [comment]
> By dump folder you mean the pre/post enqueue buffer folders? Since you hardcoded those locations in the run.py script?

I think you'd usually want the entire ".../CLIntercept_Dump/<process name>" directory since this would get you the replay information itself plus the dumped buffers and images.

> If for some reason you need to dump all the binary buffers beforehand, you know have a 100GB reproducer, not ideal I would say.

Yeah, this definitely would not be ideal.  😄 

If you have dumped all binary buffers beforehand then I think you would either a) want to be more selective about which folders you choose to construct a reproducer, which admittedly does add the possibility of making a mistake, or b) re-do the capture into a clean directory without any controls additional controls set to dump buffers, which will only dump the buffers that are needed for replay.

In practice I think I'd almost always do (b), but that's also because I'd prefer not to have 100GB dump directories lying around that I will inevitably forget about!

> If I may ask, what's the problem you're trying to solve by not dumping into the replay folder? All the ugly code duplication to figure out the right folder to dump them into?

Good question.  Reducing code duplication was my primary goal - I figured we already had existing code to dump buffers (and images) before and after a kernel enqueue, so why not just use it as-is?

It also seemed a little inconsistent to me to have the replay script look in the replay directory for the source buffers, but the capture-and-validate script look in the post-enqueue dump folders to find the destination buffers to validate against.  If we do decide to revert this part of the change and to put the source buffers in the replay directory, I think I'd also want to put the output buffers to validate against in the replay directory, also.

**Comment by Novermars** [comment]
>It also seemed a little inconsistent to me to have the replay script look in the replay directory for the source buffers, but the capture-and-validate script look in the post-enqueue dump folders to find the destination buffers to validate against.

The capture-and-validate script was very much an afterthought after I had been bitten by differing buffers a few times and wanted something quickly that used the already existing controls :) So yes, it's very far from elegant and I fully agree with your criticism. 

From the user's perspective, the way it works right now is super easy. You specify which enqueue(s) you want to dump, run the program and then you have everything (somewhat) neatly in one place, ready to zip and share and no chance that you forget to put something in there. It's in my opinion too convenient to change and would even say it's an USP of the replay functionality. For me it definitely was, after having it done this way

The code duplication is also something I wasn't happy with, but when I tried to refactor it I just made it more complex if I wanted to keep the current behavior.

>If you have dumped all binary buffers beforehand then I think you would either a) want to be more selective about which folders you choose to construct a reproducer, which admittedly does add the possibility of making a mistake, or b) re-do the capture into a clean directory without any controls additional controls set to dump buffers, which will only dump the buffers that are needed for replay.

Or c) have it all together which bypasses this problem all together :) Then it also doesn't matter if you delete the 100GB of buffers to free up space and then you would have to run the program again to get the right buffers.

>If we do decide to revert this part of the change and to put the source buffers in the replay directory, I think I'd also want to put the output buffers to validate against in the replay directory, also.

Full agree on this one!

**Comment by bashbaug** [comment]
OK, I'm convinced.  I'll try to find a clean way to put the input buffers for replay and the output buffers for validation into the same replay directory so it is a self-contained reproducer.

How would you feel about moving the validation functionality into the replay script as well, then?  It seems like this should be possible, especially if everything is in the same replay directory.

**Comment by bashbaug** [comment]
I have a solution I'm happy with - please take a look.

In short:
* The input buffers (and images) for replay and the output buffers for validation are now both placed into a sub-directory of the replay directory so the replay directory is a fully self-contained reproducer.
* The test buffers generated during replay also get placed into a sub-directory of the replay directory.
* The file naming scheme follows the naming scheme for ordinary buffer dumps, as much as possible, so it should feel familiar.
* If controls are set to dump buffers also then the buffers will be dumped in both places, as expected.

**Comment by Novermars** [comment]
I have been traveling nonstop since mid January (until early March), so still haven't been able to compile and test myself, apologies!

The changes you describe sound very good, from a quick look on my phone the code is also a lot cleaner, nice! If you want I can find some time to have a go with it, probably not until later this week though.

I'll be in the Bay Area until early March, if you happen to be in the area, feel free to send me a message! Björn can give you my personal email address :)

**Comment by seung-woo** [comment]
@bashbaug - Do you have a readme or instructions about how to capture the specific OpenCL calls and replay it? I am working on isolating and analyzing Adobe Premiere Pro's OpenCL kernels. I have a list of kernels I need to drill down, but the app itself is huge it's not practical to look at it there. Creating a reproducer is also a huge effort. This tool seems to fit the bill.

**Comment by bashbaug** [comment]
Yes, I do - please have a look at the "capture single kernels" doc in this PR:
https://github.com/bashbaug/opencl-intercept-layer/blob/more-capture-replay-controls/docs/capture_single_kernels.md

I'd be very interested in your feedback, so please let me know if anything is missing or unclear.  Thanks!

**Comment by bashbaug** [comment]
This has been working well for me so I am going to go ahead and merge this.  Please feel free to file new issues if you encounter any problems or have additional suggestions for improvement - thanks!

**Pull request merged**
